name: Pull Request Checks

on:
    pull_request

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Poetry
              uses: ./.github/actions/setup-poetry
            - name: Run ruff
              run: poetry run ruff check

    type-check:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Poetry
              uses: ./.github/actions/setup-poetry
            - name: Run mypy
              run: poetry run mypy src/ tests/

    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Poetry
              uses: ./.github/actions/setup-poetry
            - name: Test with pytest
              run: poetry run pytest tests/
